### ISSUE TITLE
Dmesg notice

### ISSUE THREAD

**Issue by mikef-nz** [floft/BellSystem#1]
Hi,

I've noticed on Raspian Stretch I get a warning reviewing the dmesg output after boot:

`[    2.360743] systemd[1]: Configuration file /lib/systemd/system/bellsystem.service is marked executable. Please remove executable permission bits. Proceeding anyway.
`
I assume it's safe just to remove that executable bit?

Mike

**Comment by floft** [comment]
Yeah, you can remove the executable bit. I set it wrong in the Makefile. I'll change it to install as 644 not 755.
