### ISSUE TITLE
GPIO relay issues

### ISSUE THREAD

**Issue by kakajaja** [floft/BellSystem#3]
Hello,
I am trying to set-up bell system with GPIO controllable relay, but the relay doesn't trigger when supposed to by schedule, or triggers, but gets stuck on always on (even if rpi is restarted(it switches off for a second, while rpi is starting up) or relay cables replugged).

Raspberry Pi 4 4GB RAM on Raspbian Buster with desktop and recommended software.
Relay - [https://www.anodas.lt/1-kanalo-rele-modulis-low-level-trigger](https://www.anodas.lt/1-kanalo-rele-modulis-low-level-trigger)

**Comment by floft** [comment]
Maybe try setting the pin high/low via some command in the terminal. If that does work but it doesn't work in the bell system schedule, then my guess would be some permissions issues, e.g. maybe the user you run the daemon as doesn't have permission to set GPIO high/low. Alternatively, maybe the schedule isn't running, e.g. if it's outside of the start/end dates.
